# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7778526e0e7f9fee1f23de25ad9646a53dcbc3ff855baa1e2e44fa41b79c8cbd80fd3595b103e118587ef2496d126ae8b72a1050dd82c43bad0fb9c977062ee9

test:
  secret_key_base: 924d519a40bd3ea85966e9ebcd433c38bd63e501b76531caf408ac92cc6afc23fed749036cdc768c4fb6b1765fd3e15ee9055f78d256ca58317dc56d17eaf270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
